
        tailwind.config = {
            darkMode: "class",
            theme: {
                extend: {
                    "colors": {
                        "inverse-primary": "#732ee4",
                        "primary": "#d2bbff",
                        "outline": "#958da1",
                        "surface-bright": "#39383e",
                        "background": "#131318",
                        "primary-fixed-dim": "#d2bbff",
                        "tertiary": "#4edea3",
                        "on-tertiary": "#003824",
                        "on-tertiary-fixed": "#002113",
                        "surface": "#131318",
                        "on-secondary-fixed": "#001a42",
                        "surface-container": "#1f1f25",
                        "on-primary-fixed": "#25005a",
                        "on-surface-variant": "#ccc3d8",
                        "surface-tint": "#d2bbff",
                        "tertiary-container": "#007650",
                        "inverse-surface": "#e4e1e9",
                        "on-secondary-fixed-variant": "#004395",
                        "on-error": "#690005",
                        "surface-container-highest": "#35343a",
                        "secondary-fixed-dim": "#adc6ff",
                        "surface-variant": "#35343a",
                        "on-tertiary-container": "#76ffc2",
                        "inverse-on-surface": "#303036",
                        "error": "#ffb4ab",
                        "on-error-container": "#ffdad6",
                        "surface-dim": "#131318",
                        "on-primary-container": "#ede0ff",
                        "on-background": "#e4e1e9",
                        "on-surface": "#e4e1e9",
                        "tertiary-fixed-dim": "#4edea3",
                        "on-primary": "#3f008e",
                        "primary-fixed": "#eaddff",
                        "tertiary-fixed": "#6ffbbe",
                        "surface-container-high": "#2a292f",
                        "on-primary-fixed-variant": "#5a00c6",
                        "primary-container": "#7c3aed",
                        "surface-container-lowest": "#0e0e13",
                        "on-secondary-container": "#e6ecff",
                        "on-secondary": "#002e6a",
                        "surface-container-low": "#1b1b20",
                        "secondary-container": "#0566d9",
                        "error-container": "#93000a",
                        "secondary-fixed": "#d8e2ff",
                        "secondary": "#adc6ff",
                        "outline-variant": "#4a4455",
                        "on-tertiary-fixed-variant": "#005236"
                    },
                    "borderRadius": {
                        "DEFAULT": "0.25rem",
                        "lg": "0.5rem",
                        "xl": "0.75rem",
                        "full": "9999px"
                    },
                    "spacing": {
                        "margin-mobile": "20px",
                        "stack-md": "16px",
                        "unit": "8px",
                        "stack-sm": "8px",
                        "container-max-width": "1200px",
                        "margin-desktop": "48px",
                        "gutter": "24px",
                        "stack-lg": "32px"
                    },
                    "fontFamily": {
                        "label-sm": ["Geist"],
                        "headline-lg": ["Geist"],
                        "body-lg": ["Geist"],
                        "headline-md": ["Geist"],
                        "display": ["Geist"],
                        "body-md": ["Geist"],
                        "label-md": ["Geist"],
                        "headline-lg-mobile": ["Geist"]
                    },
                    "fontSize": {
                        "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
                        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.03em", "fontWeight": "600" }],
                        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400" }],
                        "headline-md": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.02em", "fontWeight": "600" }],
                        "display": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700" }],
                        "body-md": ["16px", { "lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "400" }],
                        "label-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.02em", "fontWeight": "500" }],
                        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }]
                    }
                },
            },
        }
    